Traceback (most recent call last):
  File "/home/eric_guoxy/anaconda3/envs/venv/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: clip() received an invalid combination of arguments - got (float, float, out=NoneType), but expected one of:
 * (Tensor min = None, Tensor max = None)
 * (Number min = None, Number max = None)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/Acer/Desktop/大学生活/拓展学习/人工智能/RL/easyrl/proj3/train.py", line 91, in <module>
    trainer.train()
  File "/mnt/c/Users/Acer/Desktop/大学生活/拓展学习/人工智能/RL/easyrl/proj3/train.py", line 27, in train
    next_state, reward, done, _ = env.step(action) # 更新环境参数
                                  ^^^^^^^^^^^^^^^^
  File "/home/eric_guoxy/anaconda3/envs/venv/lib/python3.11/site-packages/gym/wrappers/time_limit.py", line 60, in step
    self.env.step(action),
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eric_guoxy/anaconda3/envs/venv/lib/python3.11/site-packages/gym/wrappers/order_enforcing.py", line 37, in step
    return self.env.step(action)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eric_guoxy/anaconda3/envs/venv/lib/python3.11/site-packages/gym/wrappers/step_api_compatibility.py", line 52, in step
    step_returns = self.env.step(action)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eric_guoxy/anaconda3/envs/venv/lib/python3.11/site-packages/gym/wrappers/env_checker.py", line 37, in step
    return env_step_passive_checker(self.env, action)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eric_guoxy/anaconda3/envs/venv/lib/python3.11/site-packages/gym/utils/passive_env_checker.py", line 222, in env_step_passive_checker
    result = env.step(action)
             ^^^^^^^^^^^^^^^^
  File "/home/eric_guoxy/anaconda3/envs/venv/lib/python3.11/site-packages/gym/envs/classic_control/pendulum.py", line 129, in step
    u = np.clip(u, -self.max_torque, self.max_torque)[0]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 180, in clip
  File "/home/eric_guoxy/anaconda3/envs/venv/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 2154, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eric_guoxy/anaconda3/envs/venv/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eric_guoxy/anaconda3/envs/venv/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
                     ^^^^^^^^^^^^
  File "/home/eric_guoxy/anaconda3/envs/venv/lib/python3.11/site-packages/torch/_tensor.py", line 1194, in __array__
    return self.numpy()
           ^^^^^^^^^^^^
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
